### ISSUE TITLE
Ноды соединяются перед началом общения.

### ISSUE THREAD

**Issue by Aloomenon** [Raildoc1/WebLab3#3]
Ноды не должны соединяться до того момента, как они начали общаться.

**Comment by Raildoc1** [comment]
а как сделать иначе? А если пользователь заходит в чат и ничего не пишет, а просто читает, он же не будет получать никаких сообщений

**Comment by Aloomenon** [comment]
> а как сделать иначе? А если пользователь заходит в чат и ничего не пишет, а просто читает, он же не будет получать никаких сообщений

Все верно. Пока сам писать не начал - ничего не получает.

**Comment by Aloomenon** [comment]
Получается, что до отправки какого-то сообщения, у вас уже может получиться развалившееся дерево, если оставить вариант с соединением.

**Comment by Raildoc1** [comment]
Почему? Даже если кто-то отвалится, после попытки прислать ему сообщение дерево перестроится и все ноды получат все сообщения.

**Comment by Aloomenon** [comment]
Оставьте ноду без сообщений на пол часа. Остальным нодам сделайте прцоент потерь 50. Через пол часа напишите. Какое поведение считаем нормальным?

**Comment by Raildoc1** [comment]
Ну если нода долго не отвечает, то она считается отключившейся, по-моему, вполне нормальное поведение, а так сейчас придется всю лабу переписывать

**Comment by Aloomenon** [comment]
Миллион раз это условие обсуждалось.

**Comment by Raildoc1** [comment]
всё, исправил
